server {
    listen 80;
    server_name localhost site1.local nghvtuan.id.vn;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Định tuyến API sang container Node-RED
    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name site2.local;

    location / {
        default_type text/html;
        return 200 '<html><body><h1>Website 2 - nghvtuan.id.vn</h1></body></html>';
    }
}
